### ISSUE TITLE
Check for permissions in Vue-Router

### ISSUE THREAD

**Issue by Cholowao** [stalniy/casl-vue-api-example#1]
I can be able to check for permission using `v-if`-thing. But if I try to add `beforeEach` hook in `app.js`, the `this.$can()` become undefined.

How can I use this library to test in `beforeEach` as `router` must be defined before the `Vue()` is initialized

**Comment by stalniy** [comment]
Just use `Ability` instance directly.

```js
import { ability } from '...'

const router = new Router(....)

router.beforeEach(...)
```

**Comment by Cholowao** [comment]
You are amazing

**Comment by boriszhilko** [comment]
@stalniy when i do that and access page through button click (menu item, for example), it works. But when i access page directly (adding relative link to the end of root url, e.g. i'm on localhost and i paste /page1 in the end and hit Enter) ability.cannot('access', 'page1') returns 'true' even though i have permission to access that page. Any idea why that can happen?
